mha:
  build: mha
  links:
    - master1:master_1
    - master2:master_2
    - slave1:slave_1
    - slave2:slave_2
#  command: masterha_check_repl --conf=/etc/mha.conf && masterha_manager --conf=/etc/mha.conf
master1:
  build: master
master2:
  build: slave
  links:
    - master1:master_1
slave1:
  build: slave
  links:
    - master1:master_1
    - master2:master_2
slave2:
  build: slave
  links:
    - master1:master_1
    - master2:master_2
